apiVersion: v1
kind: Service
metadata:
  name: atsea-appserver
  namespace: default
  annotations:
    description: "Internal service for application server access"
spec:
  selector:
    app: atsea-appserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
