apiVersion: apps/v1
kind: Deployment
metadata:
  name: atsea-appserver
  namespace: default
  annotations:
    description: "Spring Boot application server with React frontend"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atsea-appserver
  template:
    metadata:
      labels:
        app: atsea-appserver
    spec:
      initContainers:
        - name: wait-for-db
          image: bitnami/postgresql:latest
          command:
            - sh
            - -c
            - |
              until pg_isready -h atsea-database -p 5432 -U gordonuser -d atsea; do
                echo "Waiting for database..."
                sleep 2
              done
      containers:
        - name: appserver
          image: dockersamples/atsea_app:latest
          ports:
            - containerPort: 8080
          args: ["--spring.profiles.active=postgres"]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://atsea-database:5432/atsea
            - name: SPRING_DATASOURCE_USERNAME
              value: gordonuser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: PAYMENT_SERVICE_URL
              value: http://atsea-payment:8080
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
