apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-atsea-appserver
  namespace: default
  annotations:
    description: "Automatically scale atsea-appserver based on CPU usage"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atsea-appserver
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
