apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-messages
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cleanup
              image: todo-backend:latest
              command: ["./server", "cleanup"]
          restartPolicy: OnFailure
