apiVersion: batch/v1
kind: Job
metadata:
  name: analyze-messages
spec:
  template:
    spec:
      containers:
        - name: analyze
          image: todo-backend:latest
          command: ["./server", "analyze"]
      restartPolicy: Never
