apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-ingress-role
subjects:
- kind: ServiceAccount
  name: storage-ingress-manager
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: manage-ingressclasses
  apiGroup: rbac.authorization.k8s.io