apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-storage-role
subjects:
- kind: ServiceAccount
  name: storage-ingress-manager
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: manage-storageclasses
  apiGroup: rbac.authorization.k8s.io