apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-atsea-reverse-proxy
  namespace: default
  annotations:
    description: "Automatically scale atsea-reverse-proxy based on CPU usage"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: atsea-reverse-proxy
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
