apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  annotations:
    description: "Stores PostgreSQL database credentials"
type: Opaque
data:
  postgres-password: cGFzc3dvcmQ=  # base64 for: password
