apiVersion: apps/v1
kind: Deployment
metadata:
  name: atsea-visualizer
  namespace: default
  annotations:
    description: "Visualizer for monitoring application metrics"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atsea-visualizer
  template:
    metadata:
      labels:
        app: atsea-visualizer
    spec:
      containers:
        - name: visualizer
          image: dockersamples/atsea_visualizer:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
